<form id = "universal" class="wrapper" action = "/search/universal" method="post">
<input type = 'text' id = 'universalSearch' name='universalSearch' size = '50' placeholder="Enter Name, Show Title, or Position to search" />
<input type = 'button' id = 'universalSearchSubmit' value='Search' />
</form>
<script type = 'text/javascript'>
$(function(){
	var watermark = 'Enter Name, Show Title, or Position to search';
	$('#universalSearch').val(watermark).addClass('watermark');
	
	$('#universalSearch').focus(function()	{
		if ($(this).val() == $(this).attr('placeholder'))	{
			$(this).val('').removeClass('watermark');
		}
	});

	$('#universalSearch').autocomplete({
		source: "<?=$this->basePath('/ajax?action=UniversalSearch:search&format=json&limit=15')?>",
		minLength: 3,
		select: function(event, ui) {
			//just in case, set up the select value
			$(this).val(ui.item.label);
			
			//set variables
			var table = ui.item.table;			
			var link = ui.item.link;
		
			//in case user choose name or show titles, redirect
			if (table == 'Accounts' || table == 'Titles'){
				$(location).attr('href',link);				
			}
			
			//attach a form to the document body for positions search
			if (table == 'Positions'){
				var _id = ui.item.id;
				var _val = ui.item.value;		
				$('<form id = "hidden" action="/search/experience" method="post" style="display: none;"><input type = "hidden" name="universalPositionID" id = "universalPositionID"><input type = "hidden" id = "universalPosition" name ="universalPosition"></form>').appendTo('body');			
				$("#universalPositionID").val(_id);
				$("#universalPosition").val(_val);			
				$('#hidden').submit();						
			}			
		}		
	});
	
	$('#universalSearchSubmit').click(function(){
		//validate the input
		if ($('#universalSearch').val() == ''||$('#universalSearch').val() == watermark){
			return false;
		}
		$('#universal').submit();	
	});	
});
</script>